### ISSUE TITLE
Can you share your '/data/'?

### ISSUE THREAD

**Issue by ZJL-UCAS** [miccio-dk/smc_seminar_2019#1]
Thans for your sharing.I can not link the remote location /home/rmicci18/hrtf_i/data/, so can you upload it or email me?
Thanks!

**Comment by miccio-dk** [comment]
Hi! thanks for you interest. 

You can find the data here: https://we.tl/t-pTKocGtOtd 
Here you can find the csv with the anthropometric data as well as the pre-processed HRTF dataset, stored as a 3-dimensional MATLAB matrix of dimensions [Azimuth, Elevation, Frequency bin]. 
I left out the pinna renderings to save space, but don’t hesitate to ask me if you’d like these as well.

The link will only work for a limited period of time, if anybody is reading this from the future, feel free to reopen the issue and inquire again.

Also, go ahead and check our complete structural model, which combines pinna response synthesis with measured head-and-torso response and ITD matching.
You can find it here: https://github.com/miccio-dk/itsadive_hybrid_structural_model/ 
A conference paper describing the system will be issued soon.

**Comment by DuanZzz** [comment]
The data link is invalid, can you share it again？ Thank you
